### ISSUE TITLE
Difference between boundingBox and areaOfInterest query parameters

### ISSUE THREAD

**Issue by gerritsj** [DigitaleDeltaOrg/dd-grid-api#12]
The coverages/{coverageId}/data endpoint accepts query parameters boundingBox and areaOfInterest. The difference is not clear to me when I read the documentation.

**Comment by stefhummel** [comment]
Actually I wonder whether we should support the areaOfInterest in this first version. The WKT-string facilitates asking for data on an arbitrary polygon, which might be quite difficult to implement.

**Comment by caspervdw** [comment]
I'd like only the boundingBox, and not the areaOfInterest. Grids are rectangular.

**Comment by stefhummel** [comment]
(During team discussion)
For now, we will not support the areaOfInterest
