### ISSUE TITLE
Default and list of values for query parameter realization

### ISSUE THREAD

**Issue by gerritsj** [DigitaleDeltaOrg/dd-grid-api#13]
For the end point coverages/{coverageId}/data the query parameter realization should be optional, with all realizations as a default.

The user may want to get multiple realizations, such as [0,1,2,3,4,5], [0-10] (or even [1-5, 10-15].

**Comment by stefhummel** [comment]
(During team discussion)
Indeed offer the option of requesting for multiple realizations
Default: provide all realizations. For now only supported by providing .../data?realization=0,1,2,3,4,5
