### ISSUE TITLE
Make retrieving actual data in DD-API and DD-GRID-API consistent

### ISSUE THREAD

**Issue by gerritsj** [DigitaleDeltaOrg/dd-grid-api#14]
In the DD-GRID-API actual data can be retrieved with the /data end point. In the DD-API actual data is retrieved by including the startTime and endTime query paramaters. This should be made consistent.

Personally, I think that the DD-API should be changed since a different response should be triggered by a different end point, not by adding query parameters.

**Comment by GeriWolters** [comment]
Agreed, but this may also impact the DD-OPER-API. Splitting the endpoint for different responses for this endpoint is already mentioned in #10 or is this concerning another endpoint?

**Comment by stefhummel** [comment]
Issue #10 is about introducing an additional end point for retrieving one time series for one or more point in the grid

**Comment by stefhummel** [comment]
(During team discussion)
Close issue here, make new issue in DD-API.

**Comment by stefhummel** [comment]
DD-API is created: [https://github.com/DigitaleDeltaOrg/dd-api/issues/23](https://github.com/DigitaleDeltaOrg/dd-api/issues/23)
