### ISSUE TITLE
Add analysisStartTime and analysisEndTime as query parameters

### ISSUE THREAD

**Issue by stefhummel** [DigitaleDeltaOrg/dd-grid-api#17]
It should be possible to search for a range of analysisTimes. So we (Deltares) would suggest to add analysisStartTime and analysisEndTime as query parameters on /coverages.
Otherwise there is no way to know which analysisTimes are available without requesting all meta data.
To avoid confusion it can replace the existing analysisTime query parameter. If interested in only one specific time, start and end can be set to the same time stamp.

**Comment by GeriWolters** [comment]
What would be the default values or behaviour? (See #15)

**Comment by stefhummel** [comment]
The default value is this case is simple: return the list of available coverages without filtering on analysisTime (but probably with filtering on other attributes).

**Comment by stefhummel** [comment]
(After team discussion)
We will not formalize these parameters but will leave it up to the implementing system to offer this functionality by means of the generic filtering mechanism as defined in the DD-API
