### ISSUE TITLE
Realization string Id instead of realization index?

### ISSUE THREAD

**Issue by stefhummel** [DigitaleDeltaOrg/dd-grid-api#18]
In FEWS, a member of ensemble run has an ensemble member id, which is a string. In the DD-GRID-API it is an integer. To support string id's, we could simply redinen 'realization' as string instead of int, because the integer index value would perfectly fit into a string. However, this leads to problems in defining the realization axis in the 'envelope' and 'domainSet'.
To be discussed.

**Comment by GeriWolters** [comment]
The purpose of the id, I guess, would be an immutable identifier, while Id actually is an index? In that case, would an additional property instead of the string id make sense? Perhaps ExternalKey?

**Comment by stefhummel** [comment]
(After team discussion)
We will make the realization 'index' a string.
How to express the axis in the meta data is yet to be elaborated.
For requesting the data for a certain realization, we will use the generic filtering mechanism as defined in the DD-API.
In fact this has to be adjusted also in the DD-API. We will create an issue for this.
