### ISSUE TITLE
Link naar gegenereerde documentatie werkt niet

### ISSUE THREAD

**Issue by stefhummel** [DigitaleDeltaOrg/dd-grid-api#22]
In de top level readme.md file werkt onderstaande link niet:
  'De m.b.v. RapiDoc uit de OAS3-specificatie **gegenereerde documentatie**.'

**Comment by GeriWolters** [comment]
Opgelost. Redocly gebruikt om realtime de documentatie te genereren. Note: er moet altijd de raw versie van de spec worden gebruikt, niet de github versie: daar zit namelijk een heleboel HTML omheen.
