### ISSUE TITLE
Genereer leesbare html uit de OAS3-specificatie

### ISSUE THREAD

**Issue by stefhummel** [DigitaleDeltaOrg/dd-grid-api#7]

**Comment by GeriWolters** [comment]
The following HTML should do the trick:

<!doctype html> 
<html>
<head>
  <meta charset="utf-8"> 
  <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
</head>
<body>
  <rapi-doc spec-url = "https://raw.githubusercontent.com/DigitaleDeltaOrg/dd-grid-api/master/dd-grid-api-oas3.json"> </rapi-doc>
</body> 
</html>

See https://mrin9.github.io/RapiDoc/api.html for customization options.
