### ISSUE TITLE
Rename outputCrss endpoint

### ISSUE THREAD

**Issue by caspervdw** [DigitaleDeltaOrg/dd-grid-api#9]
I find the shorthand `Crs` in the endpoint and queryparameters a bit awkward. I'd rather rename it to the more readable `projection` throughout.

Also in the response, we use `srsName`.

**Comment by GeriWolters** [comment]
projections (plural) would be more in line with the rest of the API. The name will definitely be more clearer then.

**Comment by gerritsj** [comment]
I agree that projections is a much clearer name than Crss.

It would be better if the naming in the response and the query are consistent.

**Comment by stefhummel** [comment]
(During team discussion)
Rename outputCrs to projection, both for query parameter in .../data and for /outputCrss end point

**Comment by stefhummel** [comment]
Currently, the projection of the _domainSet_ of a coverage is still named _srsName (spatial reference system name).
Should we rename this attribute to _projection_, to be consistent with the _/projections_ end point and the _projection_ query parameter?

**Comment by gerritsj** [comment]
I prefer consistency and I think that projection is more clear than srsName.
